name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup QEMU/binfmts
      run:
        sudo apt-get update &&
        sudo apt-get install -y binfmt-support qemu qemu-user-static qemu-system-arm &&
        sudo update-binfmts --enable
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        default: true
    - name: cross build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --verbose --target=arm-unknown-linux-gnueabi
    - name: cross test
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --verbose --target=arm-unknown-linux-gnueabi
    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings -A incomplete_features

build_stable:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup QEMU/binfmts
      run:
        sudo apt-get update &&
        sudo apt-get install -y binfmt-support qemu qemu-user-static qemu-system-arm &&
        sudo update-binfmts --enable
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        default: true
    - name: cross build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --verbose --target=arm-unknown-linux-gnueabi --package example-arc
    - name: cross test
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --verbose --target=arm-unknown-linux-gnueabi --package ni-fpga
